CREATE OR REPLACE VIEW wgs_full_wide_metadata
    AS
SELECT
iso.user_isolate_id,
iso.alternative_isolate_ids,
sam.sample_collector_sample_id,
-- WGS fields
wgs.user_library_id,
wgs.experimental_protocol_field,
wgs.experimental_specimen_role_type,
wgs.nucleic_acid_extraction_method,
wgs.nucleic_acid_extraction_kit,
wgs.sample_volume_measurement_value,
wgs.sample_storage_duration_unit,
wgs.residual_sample_status,
wgs.sample_storage_duration_value,
wgs.sample_volume_measurement_unit,
wgs.nucleic_acid_storage_duration_value,
wgs.nucleic_acid_storage_duration_unit,
wgs.sequenced_by,
wgs.sequencing_date,
wgs.sequenced_by_contact_name,
wgs.sequenced_by_contact_email,
wgs.sequenced_by_laboratory_name,
wgs.sequencing_project_name,
wgs.sequencing_platform,
wgs.sequencing_instrument,
wgs.sequencing_assay_type,
wgs.dna_fragment_length,
wgs.genomic_target_enrichment_method,
wgs.genomic_target_enrichment_method_details,
wgs.amplicon_pcr_primer_scheme,
wgs.amplicon_size,
wgs.sequencing_flow_cell_version,
wgs.library_preparation_kit,
wgs.sequencing_protocol,
wgs.r1_fastq_filename,
wgs.r2_fastq_filename,
wgs.fast5_filename,
wgs.genome_sequence_filename,
wgs.r1_irida_id,
wgs.r2_irida_id,
--Extra isolate fields
iso.organism,
iso.microbiological_method,
iso.progeny_isolate_id,
iso.isolated_by,
iso.isolated_by_contact_name,
iso.isolated_by_contact_email,
iso.isolated_by_lab_name,
iso.isolation_date,
iso.isolate_received_date,
iso.taxonomic_identification_process,
iso.taxonomic_identification_process_details,
iso.serovar,
iso.serotyping_method,
iso.phagetype,
iso.irida_project_id,
iso.irida_sample_id,
iso.bioproject_id,
iso.biosample_id,
--Project fields
sam.project_name,
sam.project_description,
sam.sample_plan_id,
sam.sample_plan_name,
--Collection information fields
sam.original_sample_description,
sam.sample_collected_by,
sam.sample_collector_contact_name,
sam.sample_collector_contact_email,
sam.sample_collector_laboratory_name,
sam.sample_collection_date,
sam.sample_collection_date_precision,
sam.presamping_activity,
sam.presampling_activity_details,
sam.purpose_of_samping,
sam.sample_received_date,
sam.specimen_processing,
sam.sample_storage_method,
sam.sample_storage_medium,
sam.collection_device,
sam.collection_method,
sam.specimen_processing_details,
sam.sample_collection_end_date,
sam.sample_processing_date,
sam.sample_collection_start_time,
sam.sample_collection_end_time,
sam.sample_collection_time_of_day,
sam.sample_collection_time_duration_value,
sam.sample_collection_time_duration_unit,
--Geo fields
sam.geo_loc_country,
sam.geo_loc_state_province_region,
sam.geo_loc_latitude,
sam.geo_loc_longitude,
sam.geo_loc_name_site,
--Env fields
sam.air_temperature,
sam.air_temperature_units,
sam.water_depth,
sam.water_depth_units,
sam.water_temperature,
sam.water_temperature_units,
sam.sediment_depth,
sam.sediment_depth_units,
sam.available_data_type_details,
sam.available_data_types,
sam.animal_or_plant_population,
sam.environmental_materials,
sam.environmental_material_constituent,
sam.environmental_sites,
sam.sampling_weather_conditions,
sam.presampling_weather_conditions,
sam.precipitation_measurement_value,
sam.precipitation_measurement_unit,
sam.precipitation_measurement_method,
--Anatomical fields
sam.body_product,
sam.anatomical_material,
sam.anatomical_part,
sam.anatomical_region,
--Host fields
sam.host_common_name,
sam.host_scientific_name,
sam.host_ecotype,
sam.host_breed,
sam.host_food_production_name,
sam.host_disease,
sam.host_age_bin,
sam.host_origin_geo_loc_name_country,
--Food fields
sam.food_product_origin_country,
sam.food_product_production_stream,
sam.food_packaging_date,
sam.food_quality_date,
sam.label_claim,
sam.food_packaging,
sam.food_product,
sam.food_product_properties,
sam.animal_source_of_food
FROM
wgs_wide AS wgs
  LEFT JOIN isolates_wide               AS iso ON iso.isolate_id  = wgs.isolate_id
  LEFT JOIN full_sample_metadata        AS sam ON sam.sample_id   = iso.sample_id

